import { ReminderRule } from '../../lib/db/schema';

export function seedReminderRulesFromSpec(): Omit<ReminderRule, 'id' | 'created_at' | 'updated_at'>[] {
  return [
    {
      rule_id: 'day0_scheduling',
      email_name: 'Scheduling: In-Person Study Visit Day 0',
      phase: 'day0',
      based_on_date: 'scheduled_day_0_date',
      based_on_time: 'scheduled_day_0_time',
      trigger_type: 'send_when_new_visit_scheduled',
      offset_amount: null,
      offset_unit: null,
      week_number: null,
      fixed_send_time: null,
      template_id: 'day0_scheduling',
      reschedule_template_id: 'day0_rescheduling',
      active: true,
      study_id: null,
    },
    {
      rule_id: 'day0_patternized_diet',
      email_name: 'REMINDER: Patternized Diet Starts Tomorrow — Day 0',
      phase: 'day0',
      based_on_date: 'scheduled_day_0_date',
      based_on_time: 'scheduled_day_0_time',
      trigger_type: 'relative_to_visit_date',
      offset_amount: -4,
      offset_unit: 'days',
      week_number: null,
      fixed_send_time: '09:00',
      template_id: 'day0_patternized_diet',
      reschedule_template_id: null,
      active: true,
      study_id: null,
    },
    {
      rule_id: 'day0_visit_reminder',
      email_name: 'REMINDER: Day 0 Study Visit',
      phase: 'day0',
      based_on_date: 'scheduled_day_0_date',
      based_on_time: 'scheduled_day_0_time',
      trigger_type: 'relative_to_visit_date',
      offset_amount: -1,
      offset_unit: 'days',
      week_number: null,
      fixed_send_time: '09:00',
      template_id: 'day0_visit_reminder',
      reschedule_template_id: null,
      active: true,
      study_id: null,
    },
    {
      rule_id: 'week6_habitual_diet',
      email_name: 'REMINDER: Start Your 3-Day Habitual Diet — Week 6',
      phase: 'week6',
      based_on_date: 'scheduled_day_0_date',
      based_on_time: null,
      trigger_type: 'monday_of_week_after_day0',
      offset_amount: null,
      offset_unit: null,
      week_number: 6,
      fixed_send_time: '09:00',
      template_id: 'week6_habitual_diet',
      reschedule_template_id: null,
      active: true,
      study_id: null,
    },
    {
      rule_id: 'day90_scheduling',
      email_name: 'Scheduling: In-Person Study Visit Day 90',
      phase: 'day90',
      based_on_date: 'scheduled_day_90_date',
      based_on_time: 'scheduled_day_90_time',
      trigger_type: 'send_when_new_visit_scheduled',
      offset_amount: null,
      offset_unit: null,
      week_number: null,
      fixed_send_time: null,
      template_id: 'day90_scheduling',
      reschedule_template_id: 'day90_rescheduling',
      active: true,
      study_id: null,
    },
    {
      rule_id: 'day90_patternized_diet',
      email_name: 'REMINDER: Patternized Diet Starts Tomorrow — Day 90',
      phase: 'day90',
      based_on_date: 'scheduled_day_90_date',
      based_on_time: 'scheduled_day_90_time',
      trigger_type: 'relative_to_visit_date',
      offset_amount: -4,
      offset_unit: 'days',
      week_number: null,
      fixed_send_time: '09:00',
      template_id: 'day90_patternized_diet',
      reschedule_template_id: null,
      active: true,
      study_id: null,
    },
    {
      rule_id: 'day90_visit_reminder',
      email_name: 'REMINDER: Day 90 Study Visit',
      phase: 'day90',
      based_on_date: 'scheduled_day_90_date',
      based_on_time: 'scheduled_day_90_time',
      trigger_type: 'relative_to_visit_date',
      offset_amount: -1,
      offset_unit: 'days',
      week_number: null,
      fixed_send_time: '09:00',
      template_id: 'day90_visit_reminder',
      reschedule_template_id: null,
      active: true,
      study_id: null,
    },
    {
      rule_id: 'week18_habitual_diet',
      email_name: 'REMINDER: Start Your 3-Day Habitual Diet — Week 18',
      phase: 'week18',
      based_on_date: 'scheduled_day_0_date',
      based_on_time: null,
      trigger_type: 'monday_of_week_after_day0',
      offset_amount: null,
      offset_unit: null,
      week_number: 18,
      fixed_send_time: '09:00',
      template_id: 'week18_habitual_diet',
      reschedule_template_id: null,
      active: true,
      study_id: null,
    },
    {
      rule_id: 'day180_scheduling',
      email_name: 'Scheduling: In-Person Study Visit Day 180',
      phase: 'day180',
      based_on_date: 'scheduled_day_180_date',
      based_on_time: 'scheduled_day_180_time',
      trigger_type: 'relative_to_visit_date',
      offset_amount: -14,
      offset_unit: 'days',
      week_number: null,
      fixed_send_time: '09:00',
      template_id: 'day180_scheduling',
      reschedule_template_id: 'day180_rescheduling',
      active: true,
      study_id: null,
    },
    {
      rule_id: 'day180_visit_reminder',
      email_name: 'REMINDER: Day 180 Study Visit',
      phase: 'day180',
      based_on_date: 'scheduled_day_180_date',
      based_on_time: 'scheduled_day_180_time',
      trigger_type: 'relative_to_visit_date',
      offset_amount: -1,
      offset_unit: 'days',
      week_number: null,
      fixed_send_time: '09:00',
      template_id: 'day180_visit_reminder',
      reschedule_template_id: null,
      active: true,
      study_id: null,
    },
  ];
}
